### ISSUE TITLE
Credentials issue 

### ISSUE THREAD

**Issue by Omurden** [arguseyes/argus-eyes#18] opened 2016-07-11 15:33 UTC
Hi,
I am trying to test our web site, i setup the basic configuration for the web site, it's working well. But i am getting error for the staging server Configuration is the same, just added credentials. 

PhantomJS stdout: Unable to load the address:

I thought that it's about credentials but i couldn't find any knows issues about it. 
I am using { "credentials": "john:secret" } format as mentioned in document. 

Any idea? 
Thanks.

**Comment by branneman** [comment] 2016-07-11 15:47
1. Are you using the latest version? Credentials are supported since v0.6.0
2. Is your server expecting HTTP Basic Authentication? That's the only format supported. If you've got an HTML form which needs user/pass posted to a server, it will not work.

As you can see [in the sourcecode](https://github.com/arguseyes/argus-eyes/blob/master/app/phantomjs-script.js#L36-L39) the authentication is implemented via PhantomJS' `page.settings` feature. Could you verify PhantomJS can access your page without Argus Eyes as a middleman?

You could verify that by writing your own super-easy PhantomJS script:

```js
var page = require('webpage').create();
page.settings.userName = 'john';
page.settings.password = 'secret';
page.open('http://example.com/', function(status) {
  console.log(status);
  page.render('example.com.png', {format: 'png'});
  phantom.exit();
});
```
Then see whether it prints `success` and writes a correct PNG file.

**Comment by Omurden** [comment] 2016-07-14 10:18
I am using the latest version. Ssrver is supporting basic auth. and this code above is working well. 

Now i am getting 

argus-eyes capture x2
PhantomJS errored for page: 'homepage'
[page: homepage] [1280x768] PhantomJS stdout: Global timeout (10s per page) has expired.
Saved 0 screenshots in: .argus-eyes/x2
Failed to take 1 sceenshot

**Comment by branneman** [comment] 2016-07-14 10:58
Did you run the example code with our own testing domain or with the `example.com` domain? Of course example.com will always work :)

**Comment by Omurden** [comment] 2016-07-14 11:06
:) 

Production without password is working - Argus Eyes
Staging with password is not working - Argus eyes
Staging with password is working - PhantomJS

**Comment by branneman** [comment] 2016-07-15 08:43
Ok, thanks. I'm afraid that without being able to reproduce the issue locally, I can't really help you.

Could you try to isolate the issue so I can debug it? Maybe create a very simple express server which serves a http basic auth page which fails with argus-eyes but does work with phantom.

If it's reproducible I can fix a possible bug, right now I'm blind in the darkness :)

**Comment by Omurden** [comment] 2016-07-15 08:47
Thanks Bran, i'll update you when i have time to reproduce it

**Comment by branneman** [comment] 2016-07-18 08:46
Ok, please do. I will close this issue for now.

**Closed by branneman** 2016-07-18 08:46 UTC
